export const cx = (...parts) => parts.filter(Boolean).join(' ');

export const uiTemplates = {
  text: {
    appTitle: 'hidden min-[380px]:block text-base sm:text-xl font-bold tracking-tight text-neutral-900 dark:text-white truncate',
    fieldLabel: 'flex items-center gap-2 text-sm font-medium text-neutral-700 dark:text-neutral-300 mb-3',
    compactLabel: 'text-xs font-medium text-neutral-500 uppercase tracking-wider',
    rangeLabel: 'mb-2 flex items-center justify-between text-xs font-semibold uppercase tracking-wide text-neutral-500',
    helper: 'text-xs text-neutral-400 dark:text-neutral-500 mt-1',
    helperRelaxed: 'text-xs text-neutral-400 leading-relaxed',
    cardTitle: 'flex items-center gap-2 text-sm font-semibold text-neutral-800 dark:text-neutral-200',
    cardDescription: 'mt-1 text-xs text-neutral-500 dark:text-neutral-400',
    badge: 'text-xs px-2 py-0.5 rounded-md',
    muted: 'text-neutral-500 dark:text-neutral-400',
  },
  surfaces: {
    appShell: 'min-h-[100dvh] flex flex-col bg-neutral-50 dark:bg-[#0a0a0a] text-neutral-900 dark:text-neutral-100 font-sans transition-colors duration-200',
    dragOverlay: 'fixed inset-0 z-[200] bg-blue-500/80 backdrop-blur-sm flex flex-col items-center justify-center text-white pointer-events-none px-6 text-center',
    topbar: 'sticky top-0 z-[100] bg-white/85 dark:bg-[#111]/85 backdrop-blur-xl border-b border-neutral-200 dark:border-neutral-800 px-3 sm:px-6 py-2.5 sm:py-3 app-safe-top flex flex-wrap items-center justify-between gap-2 sm:gap-3 shadow-sm',
    toolbarGroup: 'flex bg-neutral-100/80 dark:bg-[#1a1a1a]/80 rounded-full border border-neutral-200 dark:border-neutral-800 p-1',
    section: 'border border-neutral-200 dark:border-neutral-800 rounded-xl overflow-hidden bg-white dark:bg-[#0a0a0a] transition-colors',
    sectionMobileContentOnly: 'border-0 bg-transparent lg:border lg:border-neutral-200 lg:dark:border-neutral-800 lg:rounded-xl lg:overflow-hidden lg:bg-white lg:dark:bg-[#0a0a0a] transition-colors',
    sectionHeader: 'w-full items-center justify-between gap-3 p-4 sm:p-5 bg-neutral-50/50 dark:bg-[#111]/50 hover:bg-neutral-100 dark:hover:bg-[#1a1a1a] transition-colors focus:outline-none min-h-[60px] text-left',
    sectionBody: 'p-4 sm:p-5 border-t border-neutral-100 dark:border-neutral-800/50',
    sectionMobileBody: 'px-2 py-2 lg:p-5 lg:border-t lg:border-neutral-100 lg:dark:border-neutral-800/50',
    softPanel: 'rounded-xl border border-neutral-200 bg-neutral-50 p-4 dark:border-neutral-800 dark:bg-[#111]',
    actionBar: 'hidden lg:flex flex-col bg-white dark:bg-[#0a0a0a] p-5 rounded-xl shadow-sm border border-neutral-200 dark:border-neutral-800 gap-4 transition-colors',
    exportDisclosure: 'overflow-hidden rounded-xl border border-neutral-200 bg-neutral-50 dark:border-neutral-800 dark:bg-[#111]',
    exportDisclosureLight: 'overflow-hidden rounded-xl border border-neutral-200 bg-white dark:border-neutral-800 dark:bg-[#111]',
    mobileSheet: 'fixed inset-x-3 bottom-[calc(4.75rem+env(safe-area-inset-bottom))] z-[220] max-h-[78dvh] overflow-y-auto custom-scrollbar rounded-2xl border border-neutral-200 dark:border-neutral-800 bg-neutral-50 dark:bg-[#0a0a0a] px-3 pb-2 pt-0 shadow-2xl transition-all duration-300 ease-out',
    mobileSheetExport: 'fixed inset-x-3 bottom-[calc(4.75rem+env(safe-area-inset-bottom))] z-[220] max-h-[72dvh] overflow-y-auto custom-scrollbar rounded-2xl border border-neutral-200 dark:border-neutral-800 bg-neutral-50 dark:bg-[#0a0a0a] px-3 pb-2 pt-0 shadow-2xl transition-all duration-300 ease-out lg:hidden',
    mobileSheetHeader: 'sticky top-0 z-10 -mx-3 mb-2 rounded-t-2xl border-b border-neutral-200 dark:border-neutral-800 bg-white/95 dark:bg-[#111]/95 px-4 pb-1.5 pt-1 backdrop-blur-xl touch-none',
    mobileNav: 'fixed inset-x-0 bottom-0 z-[180] border-t border-neutral-200 bg-white/95 px-3 pt-2 app-safe-bottom shadow-[0_-10px_30px_rgba(0,0,0,0.08)] backdrop-blur-xl dark:border-neutral-800 dark:bg-[#0a0a0a]/95 lg:hidden',
    modalBackdrop: 'fixed inset-0 z-[300] bg-black/60 backdrop-blur-sm flex items-end sm:items-center justify-center p-0 sm:p-4',
    modalPanel: 'bg-white dark:bg-[#0a0a0a] rounded-t-2xl sm:rounded-2xl shadow-2xl w-full max-w-md max-h-[calc(100dvh-env(safe-area-inset-top))] sm:max-h-[90dvh] border border-neutral-200 dark:border-neutral-800 flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-200',
    modalHeader: 'p-4 sm:p-5 app-safe-top border-b border-neutral-100 dark:border-neutral-800 flex items-center justify-between bg-neutral-50 dark:bg-[#111] rounded-t-2xl shrink-0',
    dropdown: 'bg-white dark:bg-[#111] border border-neutral-200 dark:border-neutral-800 rounded-lg shadow-xl z-50 overflow-hidden',
    imageCard: 'bg-white dark:bg-[#0a0a0a] rounded-xl shadow-sm border border-neutral-200 dark:border-neutral-800 overflow-hidden flex flex-col',
    imageHeader: 'bg-neutral-50 dark:bg-[#111] p-3 border-b border-neutral-200 dark:border-neutral-800 text-sm font-medium text-neutral-600 dark:text-neutral-400',
    imageStage: 'p-3 sm:p-4 flex-1 flex items-center justify-center relative group min-h-[220px] sm:min-h-[250px]',
    segmentGroup: 'flex bg-neutral-100 dark:bg-[#111] border border-neutral-200 dark:border-neutral-800 rounded-lg p-1',
    segmentGroupSoft: 'flex w-full sm:w-auto bg-neutral-200/50 dark:bg-neutral-800/50 rounded-lg p-1',
    zoomOverlay: 'fixed inset-0 z-[100] flex items-center justify-center bg-black/85 backdrop-blur-sm p-3 sm:p-8 animate-in fade-in duration-200',
    zoomToolbar: 'absolute left-1/2 top-[calc(1rem+env(safe-area-inset-top))] z-10 flex -translate-x-1/2 items-center gap-2 rounded-full bg-black/60 p-1.5 text-white shadow-xl backdrop-blur-md',
    snapMenu: 'fixed z-[450] hidden w-[296px] -translate-x-1/2 overflow-hidden rounded-2xl border border-neutral-200 bg-white shadow-2xl animate-in fade-in zoom-in-95 duration-150 dark:border-neutral-800 dark:bg-[#0a0a0a] lg:block',
    snapMenuHeader: 'flex items-center justify-between gap-3 border-b border-neutral-100 px-3 py-2.5 dark:border-neutral-800',
  },
  buttons: {
    topbarIcon: 'w-11 h-11 flex items-center justify-center rounded-full bg-neutral-100/80 dark:bg-[#1a1a1a]/80 border border-neutral-200 dark:border-neutral-800 hover:bg-white dark:hover:bg-[#2a2a2a] transition-all duration-300 hover:rotate-12 active:scale-90 shadow-sm',
    toolbarIcon: 'w-11 h-11 sm:w-9 sm:h-9 flex items-center justify-center rounded-full hover:bg-white dark:hover:bg-[#2a2a2a] disabled:opacity-30 disabled:hover:bg-transparent transition-colors active:scale-95',
    closeIcon: 'flex h-9 w-9 items-center justify-center rounded-full bg-neutral-100 text-neutral-600 transition-colors active:scale-95 dark:bg-neutral-800 dark:text-neutral-300',
    modalClose: 'w-11 h-11 -mr-2 flex items-center justify-center rounded-lg hover:bg-neutral-200 dark:hover:bg-[#222] text-neutral-500 transition-colors active:scale-95',
    primary: 'flex min-h-[44px] items-center justify-center gap-2 rounded-lg bg-neutral-900 px-4 py-2.5 text-sm font-semibold text-white transition-colors active:scale-[0.98] disabled:cursor-wait disabled:opacity-60 dark:bg-white dark:text-black',
    primaryBlue: 'flex min-h-[44px] items-center justify-center gap-2 rounded-xl bg-blue-600 px-3 py-2.5 text-sm font-semibold text-white transition-colors active:scale-[0.98] disabled:cursor-not-allowed disabled:opacity-50',
    secondary: 'flex min-h-[44px] items-center justify-center gap-2 rounded-lg bg-white px-4 py-2.5 text-sm font-semibold text-neutral-700 transition-colors active:scale-[0.98] disabled:opacity-40 dark:bg-[#0a0a0a] dark:text-neutral-300',
    neutral: 'flex min-h-[44px] items-center justify-center gap-2 rounded-lg bg-neutral-200/60 px-4 py-2.5 text-sm transition-colors active:scale-[0.98] hover:bg-neutral-300 dark:bg-neutral-700/60 dark:hover:bg-neutral-600',
    success: 'flex min-h-[44px] items-center justify-center gap-2 rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white transition-colors active:scale-[0.98] disabled:cursor-wait disabled:opacity-60 dark:bg-emerald-500 dark:text-black',
    upload: 'flex items-center justify-center gap-2 bg-neutral-900 hover:bg-black dark:bg-white dark:hover:bg-neutral-200 text-white dark:text-black px-6 py-3 sm:py-2.5 rounded-lg font-medium transition-all duration-200 active:scale-95 shadow-sm min-h-[44px]',
    download: 'flex items-center justify-center gap-2 bg-emerald-600 hover:bg-emerald-700 dark:bg-emerald-500 dark:hover:bg-emerald-400 text-white dark:text-black px-5 py-2.5 rounded-lg font-medium transition-all duration-200 active:scale-95 shadow-sm min-h-[44px]',
    disclosure: 'flex min-h-[48px] w-full items-center justify-between gap-3 px-4 py-3 text-left text-sm font-semibold text-neutral-800 transition-colors hover:bg-neutral-100 dark:text-neutral-200 dark:hover:bg-neutral-900',
    disclosureLight: 'flex min-h-[48px] w-full items-center justify-between gap-3 px-4 py-3 text-left text-sm font-semibold text-neutral-800 transition-colors hover:bg-neutral-100 dark:text-neutral-200 dark:hover:bg-neutral-800',
    menuItem: 'flex items-center gap-3 px-4 py-3 min-h-[44px] hover:bg-neutral-100 dark:hover:bg-neutral-800 text-sm text-neutral-700 dark:text-neutral-300',
    mobileMenuItem: 'flex min-h-[48px] w-full items-center gap-3 px-4 py-3 text-left text-sm font-medium text-neutral-700 transition-colors hover:bg-neutral-100 dark:text-neutral-300 dark:hover:bg-neutral-800',
    mobileNavBase: 'flex min-h-[52px] flex-col items-center justify-center gap-1 rounded-xl text-[11px] font-semibold transition-colors active:scale-95',
    mobileNavActive: 'bg-neutral-900 text-white dark:bg-white dark:text-black',
    mobileNavIdle: 'text-neutral-600 dark:text-neutral-300',
    mobileNavSuccessActive: 'bg-emerald-600 text-white dark:bg-emerald-400 dark:text-black',
    mobileNavSuccessIdle: 'text-emerald-700 dark:text-emerald-300',
    mobileNavDisabled: 'text-neutral-400 opacity-60 dark:text-neutral-600',
    segmentBase: 'flex-1 sm:flex-none px-4 py-2.5 sm:py-1.5 min-h-[44px] sm:min-h-0 text-sm rounded-md transition-all',
    segmentBaseTight: 'flex-1 sm:flex-none px-4 py-2.5 sm:py-1.5 min-h-[44px] sm:min-h-0 text-xs rounded-md transition-all',
    segmentActive: 'bg-white dark:bg-neutral-800 shadow-sm text-neutral-900 dark:text-white font-medium',
    segmentInactive: 'text-neutral-500 hover:text-neutral-700 dark:hover:text-neutral-300',
    segmentActiveDark: 'bg-neutral-900 text-white dark:bg-white dark:text-black',
    choice: 'flex items-center justify-center py-3 rounded-xl border text-sm font-medium transition-all',
    choiceActive: 'bg-black dark:bg-white text-white dark:text-black border-black dark:border-white shadow-md',
    choiceIdle: 'bg-white dark:bg-[#111] border-neutral-200 dark:border-neutral-800 text-neutral-600 dark:text-neutral-400 hover:border-neutral-400',
    colorPickIdle: 'bg-neutral-50 dark:bg-[#111] border-neutral-200 dark:border-neutral-800 text-neutral-600 dark:text-neutral-400 hover:bg-neutral-100 dark:hover:bg-[#222]',
    colorPickActive: 'bg-blue-100 border-blue-400 text-blue-600 dark:bg-blue-900/30 dark:border-blue-700 dark:text-blue-400 animate-pulse',
    emptyUpload: 'flex min-h-[calc(100dvh-9.625rem-env(safe-area-inset-bottom))] w-full flex-1 flex-col items-center justify-center gap-5 rounded-none border-y border-dashed border-neutral-300 bg-white p-6 text-center shadow-sm transition-all hover:border-neutral-500 hover:bg-neutral-100/60 active:scale-[0.99] dark:border-neutral-700 dark:bg-[#0a0a0a] dark:hover:border-neutral-500 dark:hover:bg-[#111] lg:min-h-[360px] lg:rounded-2xl lg:border',
    zoomIcon: 'flex h-10 w-10 items-center justify-center rounded-full text-white/80 transition-colors hover:bg-white/15 hover:text-white',
    zoomClose: 'absolute top-[calc(1rem+env(safe-area-inset-top))] right-4 sm:top-6 sm:right-6 text-white/70 hover:text-white bg-black/50 hover:bg-black/80 rounded-full w-11 h-11 flex items-center justify-center transition-all hover:scale-110 active:scale-95 z-10',
    snapTarget: 'flex min-h-[82px] flex-col items-center justify-center gap-2 rounded-xl border p-2 text-xs font-semibold transition-all focus:outline-none focus:ring-2 focus:ring-blue-500',
    snapTargetActive: 'border-blue-400 bg-blue-50 text-blue-700 dark:border-blue-500/60 dark:bg-blue-500/15 dark:text-blue-200',
    snapTargetIdle: 'border-neutral-200 bg-neutral-50 text-neutral-700 hover:border-neutral-300 hover:bg-white dark:border-neutral-800 dark:bg-[#111] dark:text-neutral-300 dark:hover:border-neutral-700 dark:hover:bg-[#161616]',
    snapRestore: 'flex min-h-[44px] w-full items-center justify-center gap-2 rounded-xl bg-neutral-100 px-3 py-2.5 text-sm font-semibold text-neutral-700 transition-colors hover:bg-neutral-200 focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-neutral-800 dark:text-neutral-200 dark:hover:bg-neutral-700',
  },
  inputs: {
    number: 'w-16 px-2 py-1 font-normal text-sm border-2 border-neutral-300 dark:border-neutral-700 rounded outline-none shadow-inner bg-white dark:bg-[#0a0a0a] text-neutral-900 dark:text-neutral-100 focus:border-neutral-800 dark:focus:border-neutral-400 transition-colors',
    inlineNumber: 'cursor-pointer text-neutral-600 dark:text-neutral-400 hover:text-black dark:hover:text-white font-bold underline decoration-dashed underline-offset-4 transition-colors inline-flex items-center justify-center min-h-[32px] px-2 -mx-2 rounded hover:bg-neutral-100 dark:hover:bg-neutral-800/50',
    rangeBase: 'w-full h-3 sm:h-2 bg-neutral-200 dark:bg-neutral-800 rounded-lg appearance-none cursor-pointer',
    rangeNeutral: 'accent-neutral-900 dark:accent-neutral-100',
    rangeBlue: 'accent-blue-500',
    rangeEmerald: 'accent-emerald-500',
    rangeIndigo: 'accent-indigo-500',
    colorSwatchLarge: 'relative w-14 h-14 sm:w-12 sm:h-12 rounded-lg overflow-hidden border border-neutral-200 dark:border-neutral-700 shadow-sm shrink-0 cursor-pointer focus-within:ring-2 focus-within:ring-neutral-400 transition-all hover:scale-105 active:scale-95',
    colorSwatchSmall: 'relative w-10 h-10 rounded-lg overflow-hidden border border-neutral-200 dark:border-neutral-700 shrink-0 cursor-pointer focus-within:ring-2 focus-within:ring-neutral-400 transition-all hover:scale-105 active:scale-95',
    colorSwatchExport: 'relative h-11 w-11 shrink-0 overflow-hidden rounded-lg border border-neutral-200 dark:border-neutral-700',
    colorInputLarge: 'absolute -top-4 -left-4 w-24 h-24 sm:w-20 sm:h-20 cursor-pointer',
    colorInputSmall: 'absolute -top-4 -left-4 w-20 h-20 cursor-pointer',
    colorInputExport: 'absolute -left-4 -top-4 h-20 w-20 cursor-pointer',
    hex: 'bg-transparent border-b-2 border-dashed border-neutral-300 dark:border-neutral-700 outline-none text-sm font-mono font-medium text-neutral-800 dark:text-neutral-200 uppercase tracking-wider p-0 focus:ring-0 w-20 hover:border-neutral-400 dark:hover:border-neutral-500 focus:border-neutral-600 dark:focus:border-neutral-400 transition-colors',
    hexWide: 'w-24 bg-transparent border-b-2 border-dashed border-neutral-300 p-0 font-mono text-sm font-medium uppercase text-neutral-800 outline-none transition-colors focus:border-neutral-600 focus:ring-0 dark:border-neutral-700 dark:text-neutral-200',
    text: 'w-full bg-neutral-50 dark:bg-[#111] border border-neutral-200 dark:border-neutral-800 text-neutral-700 dark:text-neutral-300 rounded-xl px-4 py-3 min-h-[44px] focus:outline-none focus:ring-2 focus:ring-blue-500 text-sm',
    textMono: 'w-full bg-neutral-50 dark:bg-[#111] border border-neutral-200 dark:border-neutral-800 text-neutral-700 dark:text-neutral-300 rounded-xl px-4 py-3 min-h-[44px] focus:outline-none focus:ring-2 focus:ring-blue-500 font-mono text-sm',
    textMonoWithIcon: 'w-full bg-neutral-50 dark:bg-[#111] border border-neutral-200 dark:border-neutral-800 text-neutral-700 dark:text-neutral-300 rounded-xl pl-11 pr-12 py-3 min-h-[44px] focus:outline-none focus:ring-2 focus:ring-blue-500 font-mono text-sm',
    transparentInline: 'bg-transparent border-none outline-none text-sm font-medium text-neutral-700 dark:text-neutral-300 w-full min-w-[80px] p-0 focus:ring-0',
    filenameShell: 'flex min-h-[44px] items-center gap-2 rounded-lg border border-neutral-200 bg-neutral-50 px-3 py-2.5 transition-colors focus-within:border-neutral-400 dark:border-neutral-700 dark:bg-[#111] dark:focus-within:border-neutral-500',
    filenameShellMobile: 'flex min-h-[44px] items-center gap-2 rounded-xl border border-neutral-200 bg-white px-3 py-2.5 transition-colors focus-within:border-neutral-400 dark:border-neutral-700 dark:bg-[#111] dark:focus-within:border-neutral-500',
    textarea: 'w-full bg-neutral-50 dark:bg-[#111] border border-neutral-200 dark:border-neutral-800 text-neutral-700 dark:text-neutral-300 rounded-xl px-4 py-3 min-h-[120px] sm:min-h-[100px] resize-none focus:outline-none focus:ring-2 focus:ring-blue-500 text-sm',
    selectButton: 'w-full bg-neutral-50 dark:bg-[#111] border border-neutral-200 dark:border-neutral-800 text-neutral-700 dark:text-neutral-300 rounded-xl px-4 py-3 pr-11 min-h-[44px] focus:outline-none focus:ring-2 focus:ring-blue-500 font-medium flex items-center justify-between gap-3 text-left hover:border-neutral-300 dark:hover:border-neutral-700 transition-colors',
    selectMenu: 'absolute left-0 right-0 top-full mt-2 z-[520] overflow-hidden rounded-xl border border-neutral-200 bg-white shadow-2xl animate-in fade-in slide-in-from-top-2 duration-150 dark:border-neutral-800 dark:bg-[#0a0a0a]',
    search: 'w-full rounded-lg border border-transparent bg-neutral-50 py-2 pl-9 pr-3 text-sm text-neutral-800 outline-none transition-colors placeholder:text-neutral-400 focus:border-blue-400 focus:bg-white dark:bg-[#111] dark:text-neutral-200 dark:focus:bg-black',
  },
  toggles: {
    label: 'flex items-center gap-3 cursor-pointer text-sm font-medium text-neutral-700 dark:text-neutral-300 w-full sm:w-fit min-h-[44px] select-none group',
    labelCompact: 'flex items-center gap-3 cursor-pointer text-sm font-medium text-neutral-700 dark:text-neutral-300 w-full sm:w-fit select-none group py-3 sm:py-1',
    labelInline: 'flex min-h-[44px] cursor-pointer items-center gap-3 text-sm font-medium text-neutral-700 dark:text-neutral-300',
    track: 'relative inline-flex h-6 w-11 shrink-0 items-center rounded-full transition-colors duration-200 ease-in-out',
    trackOnBlue: 'bg-blue-500',
    trackOnIndigo: 'bg-indigo-500',
    trackOff: 'bg-neutral-300 dark:bg-neutral-600',
    thumb: 'pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow-md ring-0 transition duration-200 ease-in-out',
    thumbOn: 'translate-x-5',
    thumbOff: 'translate-x-1',
    iconLabel: 'flex items-center gap-2',
    icon: 'w-4 h-4 text-neutral-500 group-hover:text-neutral-900 dark:group-hover:text-white transition-colors',
  },
  notices: {
    stack: 'fixed bottom-[calc(1rem+env(safe-area-inset-bottom))] left-1/2 z-[500] flex w-[calc(100vw-2rem)] -translate-x-1/2 flex-col items-center gap-2 pointer-events-none sm:bottom-6 sm:w-max sm:max-w-[90vw]',
    item: 'flex w-full items-center gap-3 rounded-2xl border border-white/10 bg-neutral-900 py-2.5 pl-4 pr-2 text-sm font-medium text-white shadow-2xl transition-all pointer-events-auto animate-in fade-in slide-in-from-bottom-4 duration-300 dark:border-black/10 dark:bg-white dark:text-neutral-900',
    dismiss: 'flex h-9 w-9 shrink-0 items-center justify-center rounded-full text-neutral-400 transition-colors hover:bg-white/10 hover:text-white dark:text-neutral-500 dark:hover:bg-black/10 dark:hover:text-black',
  },
};

export const templateClasses = {
  range: (tone = 'neutral') => cx(
    uiTemplates.inputs.rangeBase,
    {
      neutral: uiTemplates.inputs.rangeNeutral,
      blue: uiTemplates.inputs.rangeBlue,
      emerald: uiTemplates.inputs.rangeEmerald,
      indigo: uiTemplates.inputs.rangeIndigo,
    }[tone] || uiTemplates.inputs.rangeNeutral
  ),
  toggleTrack: (checked, tone = 'blue') => cx(
    uiTemplates.toggles.track,
    checked
      ? tone === 'indigo' ? uiTemplates.toggles.trackOnIndigo : uiTemplates.toggles.trackOnBlue
      : uiTemplates.toggles.trackOff
  ),
  toggleThumb: (checked) => cx(uiTemplates.toggles.thumb, checked ? uiTemplates.toggles.thumbOn : uiTemplates.toggles.thumbOff),
  segmentButton: (active, tight = false, activeClass = uiTemplates.buttons.segmentActive) => cx(
    tight ? uiTemplates.buttons.segmentBaseTight : uiTemplates.buttons.segmentBase,
    active ? activeClass : uiTemplates.buttons.segmentInactive
  ),
  mobileNav: (active, { success = false, disabled = false } = {}) => cx(
    uiTemplates.buttons.mobileNavBase,
    active
      ? success ? uiTemplates.buttons.mobileNavSuccessActive : uiTemplates.buttons.mobileNavActive
      : disabled ? uiTemplates.buttons.mobileNavDisabled : success ? uiTemplates.buttons.mobileNavSuccessIdle : uiTemplates.buttons.mobileNavIdle
  ),
};
